/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Playground`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Evolution` | `/Evolution`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Health` | `/Health`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Progress` | `/Progress`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Workout` | `/Workout`; params?: Router.UnknownInputParams; } | { pathname: `/workout/Execution`; params?: Router.UnknownInputParams; } | { pathname: `/workout/ExerciseSelection`; params?: Router.UnknownInputParams; } | { pathname: `/workout/FinishSelection`; params?: Router.UnknownInputParams; } | { pathname: `/workout/Selection`; params?: Router.UnknownInputParams; } | { pathname: `/workout/Summary`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Playground`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Evolution` | `/Evolution`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Health` | `/Health`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Progress` | `/Progress`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Workout` | `/Workout`; params?: Router.UnknownOutputParams; } | { pathname: `/workout/Execution`; params?: Router.UnknownOutputParams; } | { pathname: `/workout/ExerciseSelection`; params?: Router.UnknownOutputParams; } | { pathname: `/workout/FinishSelection`; params?: Router.UnknownOutputParams; } | { pathname: `/workout/Selection`; params?: Router.UnknownOutputParams; } | { pathname: `/workout/Summary`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/Playground${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Evolution${`?${string}` | `#${string}` | ''}` | `/Evolution${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Health${`?${string}` | `#${string}` | ''}` | `/Health${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Home${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Progress${`?${string}` | `#${string}` | ''}` | `/Progress${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Workout${`?${string}` | `#${string}` | ''}` | `/Workout${`?${string}` | `#${string}` | ''}` | `/workout/Execution${`?${string}` | `#${string}` | ''}` | `/workout/ExerciseSelection${`?${string}` | `#${string}` | ''}` | `/workout/FinishSelection${`?${string}` | `#${string}` | ''}` | `/workout/Selection${`?${string}` | `#${string}` | ''}` | `/workout/Summary${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Playground`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Evolution` | `/Evolution`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Health` | `/Health`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Progress` | `/Progress`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Workout` | `/Workout`; params?: Router.UnknownInputParams; } | { pathname: `/workout/Execution`; params?: Router.UnknownInputParams; } | { pathname: `/workout/ExerciseSelection`; params?: Router.UnknownInputParams; } | { pathname: `/workout/FinishSelection`; params?: Router.UnknownInputParams; } | { pathname: `/workout/Selection`; params?: Router.UnknownInputParams; } | { pathname: `/workout/Summary`; params?: Router.UnknownInputParams; };
    }
  }
}
